### ISSUE TITLE
Companion failed to merge with "Failed to parse lockfile of polkadot" error

### ISSUE THREAD

**Issue by TriplEight** [paritytech/parity-processbot#392] opened 2022-07-05 16:06 UTC
Originally posted in [github.com/paritytech](https://github.com/paritytech/ci_cd/issues/488) by @koute 

> This substrate PR here [paritytech/substrate#11722](https://github.com/paritytech/substrate/pull/11722) had a polkadot companion here [paritytech/polkadot#5731](https://github.com/paritytech/polkadot/pull/5731). The substrate PR was all green (including the companion job), so I typed "bot merge", and I was expecting that the companion gets merged too, but it failed with a "Merge cancelled due to error. Error: Failed to parse lockfile of polkadot" error.

**Comment by joao-paulo-parity** [comment] 2022-07-06 03:53
The full error from https://github.com/paritytech/polkadot/pull/5731#issuecomment-1168307056

> Merge cancelled due to error. Error: Failed to parse lockfile of polkadot: Error { kind: Parse, msg: "parse error: ambiguous dependency: windows-sys" }

It happened in https://github.com/paritytech/parity-processbot/blob/2feca9bad88815a031c5c3c3a6b0ff9f90c2de3f/src/companion.rs#L104 and is related to `cargo_lock`. From a quick look at `cargo_lock`'s source code (https://github.com/rustsec/rustsec/tree/main/cargo-lock) so far I couldn't quite find why this error happens. It's strange since dependency resolution is cargo's job and I was expecting `cargo_lock` to only be parsing the file, but perhaps it does more.

On another note I've recently found out that `Cargo.lock` is a TOML file, so we should consider dropping `cargo_lock` in favor of parsing the lockfiles through https://crates.io/crates/toml directly.

**Comment by joao-paulo-parity** [comment] 2022-07-11 11:09
Ok, I think I figured it out. The problem is that the lockfile had two windows-sys

- https://github.com/koute/polkadot/blob/8ff2627f00c88e5f0997b44f444b67d3a83d3444/Cargo.lock#L12687

- https://github.com/koute/polkadot/blob/8ff2627f00c88e5f0997b44f444b67d3a83d3444/Cargo.lock#L12700

It was incorrect when the bot tried to merge it since the link in https://github.com/koute/polkadot/blob/8ff2627f00c88e5f0997b44f444b67d3a83d3444/Cargo.lock#L6054 doesn't correctly specify which version to use. And the follow-up commit had to fix that in https://github.com/paritytech/polkadot/pull/5731/commits/2abfa1c7435b57155aa28ecc106f547539b454c7#diff-13ee4b2252c9e516a0547f2891aa2105c3ca71c6d7a1e682c69be97998dfc87eR6054.

Therefore the problem in that case wasn't with the bot, it was with the commit itself.

That problem should've been caught by the integration checks on CI, so I've created https://github.com/paritytech/pipeline-scripts/issues/61 for this.

Closing since this isn't a processbot bug.

**Closed by joao-paulo-parity** 2022-07-11 11:09 UTC

**Comment by joao-paulo-parity** [comment] 2022-07-11 12:02
The problems mentioned here might have a solution in the future as per https://github.com/rustsec/rustsec/issues/606, but it relies on `cargo_lock` 's upstream changes; I don't think it's worthwhile for us to do something about them in processbot directly.
